name: Running tests against commits
on: [push]

jobs:
  on-commit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Running tests
        run: npm run test:unit
      - name: Running lint
        run: npm run test:lint
